services:
  postgres:
    image: postgres:16
    container_name: bank-postgres
    environment:
      POSTGRES_DB: bank_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d bank_db"]
      interval: 5s
      timeout: 5s
      retries: 10

  calculator-api:
    build:
      context: ./api/calculator-api
      dockerfile: Dockerfile
    container_name: calculator-api
    ports:
      - "8081:8081"

  deal-api:
    build:
      context: ./api/deal-api
      dockerfile: Dockerfile
    container_name: deal-api
    ports:
      - "8082:8082"
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/bank_db
      DB_USERNAME: postgres
      DB_PASSWORD: admin
      CALCULATOR_API_BASE_URL: http://calculator-api:8081
    depends_on:
      postgres:
        condition: service_healthy
      calculator-api:
        condition: service_started

volumes:
  postgres_data: