spring:
  application:
    name: statement
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/bank_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:admin}
    driver-class-name: org.postgresql.Driver

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.xml

  jpa:
    hibernate:
      ddl-auto: validate

server:
  port: '8083'

deal-api:
  base-url: ${DEAL_API_BASE_URL:http://localhost:8082}

springdoc:
  api-docs:
    enabled: 'true'
    path: /v3/api-docs
    resolve-schema-properties: 'true'
  swagger-ui:
    url: /v3/api-docs.yaml

resilience4j:
  retry:
    instances:
      dealClientRetry:
        max-attempts: 3
        wait-duration: 500ms
        retry-exceptions:
          - feign.RetryableException
          - feign.FeignException
          - ru.neo.study.statement.exception.OffersNotFoundException

  circuitbreaker:
    instances:
      dealClientCircuitBreaker:
        failure-rate-threshold: 50
        sliding-window-size: 3
        minimum-number-of-calls: 3
        permitted-number-of-calls-in-half-open-state: 1
        wait-duration-in-open-state: 10s