spring:
  application:
    name: statement
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/bank_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:admin}
    driver-class-name: org.postgresql.Driver

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.xml

  jpa:
    hibernate:
      ddl-auto: validate

server:
  port: '8083'

deal-api:
  base-url: http://localhost:8082

calculator-api:
  base-url: http://localhost:8081

springdoc:
  api-docs:
    enabled: 'true'
    path: /v3/api-docs
    resolve-schema-properties: 'true'
  swagger-ui:
    url: /v3/api-docs.yaml