spring.application.name=calculator
server.port=8081

credit-properties.loan-rate=20

credit-properties.max-count-salary=24
credit-properties.range-age-female=32,60
credit-properties.range-age-male=30,55
credit-properties.min-total-work-month=18
credit-properties.min-current-work-month=3

credit-properties.min-amount=20000
credit-properties.min-term=6

credit-properties.insurance-rate=0.1
credit-properties.large-amount-threshold=1000000
credit-properties.long-term-threshold=60
credit-properties.scale=10

discount-properties.salary-client-discount=1.0
discount-properties.insurance-discount=0.5

