spring:
  application:
    name: dossier
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

    consumer:
      group-id: dossier-consumer
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

      properties:
        spring.json.trusted.packages: "ru.neo.study.dossier.dto,ru.neo.study.dossier.enums"
        spring.json.value.default.type: "ru.neo.study.dossier.dto.EmailMessage"
        spring.json.use.type.headers: false

  mail:
    host: ${MAIL_HOST:sandbox.smtp.mailtrap.io}
    port: ${MAIL_PORT:2525}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}

    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

app:
  documents:
    storage-dir: ${DOCUMENTS_STORAGE_DIR:documents}

  mail:
    real-sending-enabled: ${MAIL_REAL_SENDING_ENABLED:true}
    from: ${MAIL_FROM:no-reply@bank.local}

  kafka:
    topics:
      finish-registration: finish-registration
      create-documents: create-documents
      send-documents: send-documents
      send-ses: send-ses
      credit-issued: credit-issued
      statement-denied: statement-denied
server:
  port: 8084

springdoc:
  api-docs:
    enabled: 'true'
    path: /v3/api-docs
    resolve-schema-properties: 'true'
  swagger-ui:
    url: /openapi.yml
    path: /swagger-ui.html
